### ISSUE TITLE
Windows phone 8.1 build error

### ISSUE THREAD

**Issue by Xonoroff** [neuecc/UniRx#66]
Hello. I am trying to build this library to windows phone 8.1 and i have error "Assets\Libraries\UniRx\Scripts\UnityEngineBridge\Triggers\ObservableTriggerExtensions.cs(111,23): error CS0246: The type or namespace name 'IObservable' could not be found (are you missing a using directive or an assembly reference?)"
How can i solve it?

Added: I had removed directive from IObservable and builded project. But in line 
 Observable.Start(Foo1()).ObserveOnMainThread().Subscribe(un =>Foo2(un);}
I have got new error (runtime error).

Exception: Specified method is not supported.
Type: System.NotSupportedException
Module: mscorlib
InnerException: <No Data>
AdditionalInfo:<No Data>
   at System.Action.BeginInvoke(AsyncCallback callback, Object object)
   at UniRx.Scheduler.ThreadPoolScheduler.Schedule(Action action)
   at UniRx.Observable.<>c__DisplayClass166.<ToAsync>b__164()
   at UniRx.Observable.Start(Action action, IScheduler scheduler)
   at UniRx.Observable.Start(Action action)

**Comment by neuecc** [comment]
Thank you and sorry for late response.
I've fixed both errors.
